use crate::ecs::World;
use crate::frame::{FlatEntity, Frame, RenderPass, PassType};

/// Compiles the ECS World's DrawCalls into a renderable Frame.
/// This Replaces the V2 `compiler.rs` payload, running pure data translations.
pub fn render_to_frame(
    world: &World,
    camera_id: &str,
    screen_width: u32,
    screen_height: u32,
    _time_secs: f64,
    custom_cam_x: Option<f32>,
    custom_cam_y: Option<f32>,
    custom_cam_w: Option<f32>,
    custom_cam_h: Option<f32>,
    scope_entity_id: Option<&str>,
) -> Frame {
    let mut passes = Vec::new();
    let mut texture_updates = Vec::new();
    let mut audio_calls = Vec::new();
    let storages = &world.storages;

    // ── Camera projection: world units → pixels ──
    let cam = world.find_camera(camera_id);
    let cam_x = custom_cam_x.unwrap_or_else(|| cam.map(|c| c.resolved.x).unwrap_or(0.0));
    let cam_y = custom_cam_y.unwrap_or_else(|| cam.map(|c| c.resolved.y).unwrap_or(0.0));
    let cam_w = custom_cam_w.unwrap_or_else(|| cam.map(|c| c.resolved.width).unwrap_or(1280.0)).max(1.0);
    let cam_h = custom_cam_h.unwrap_or_else(|| cam.map(|c| c.resolved.height).unwrap_or(720.0)).max(1.0);
    let sx = screen_width as f32 / cam_w;
    let sy = screen_height as f32 / cam_h;

    // ── Helper: check if entity is a descendant of scope ──
    let is_in_scope = |entity_id: &str| -> bool {
        if scope_entity_id.is_none() { return true; }
        let scope_id = scope_entity_id.unwrap();
        // Walk parent chain to see if any ancestor is the scope entity
        let mut current_id = entity_id.to_string();
        for _ in 0..32 { // max depth guard
            if let Some(e) = world.entities.iter().find(|e| e.id == current_id) {
                if let Some(pid) = storages.get_component::<crate::ecs::components::meta::ParentId>(&e.id).map(|id| &id.0) {
                    if pid == scope_id { return true; }
                    current_id = pid.to_string();
                } else {
                    return false; // reached root without finding scope
                }
            } else {
                return false;
            }
        }
        false
    };

    let mut camera_effects = Vec::new();
    let mut layer_effects_map = std::collections::HashMap::new();

    // Collect and sort flat entities directly from the pre-generated DrawCalls
    let mut flat_entities = Vec::new();

    let sorted = world.sorted_by_layer();
    for entity in &sorted {
        if !entity.resolved.visible { continue; }
        // Skip entities outside render scope
        if !is_in_scope(&entity.id) { continue; }
        // Camera effects are now implicitly captured because camera entities have DrawCalls 
        // generated by `editor_gizmo_sys` (so they iterate and add their effects).
        // If there's NO `editor_gizmo_sys` running, cameras might have NO `draw_calls`.
        // Wait! We MUST process `camera_effects` regardless of whether they have `draw_calls`!
        // So we will process `entity.draw.effect_chain` for ALL entities, even if they have no draws.

        // ── Process Texture Requests ──
        for req in &entity.draw.texture_requests {
            match req {
                crate::ecs::components::draw::TextureRequest::LoadImage { key, asset_url } => {
                    texture_updates.push(crate::frame::TextureUpdate::LoadImage {
                        key: key.clone(),
                        path: asset_url.clone(),
                    });
                }
                crate::ecs::components::draw::TextureRequest::LoadFont { key, asset_url } => {
                    texture_updates.push(crate::frame::TextureUpdate::LoadFont {
                        key: key.clone(),
                        path: asset_url.clone(),
                    });
                }
                crate::ecs::components::draw::TextureRequest::DecodeVideoFrame { key, asset_url, timestamp_secs } => {
                    texture_updates.push(crate::frame::TextureUpdate::DecodeVideoFrame {
                        key: key.clone(),
                        path: asset_url.clone(),
                        timestamp_secs: *timestamp_secs,
                        width: None,
                        height: None,
                    });
                }
                crate::ecs::components::draw::TextureRequest::RasterizeText { key, content, font_size, color, font_key, max_width, line_height, alignment } => {
                    texture_updates.push(crate::frame::TextureUpdate::RasterizeText {
                        key: key.clone(),
                        content: content.clone(),
                        font_size: *font_size,
                        color: *color,
                        font_key: font_key.clone(),
                        max_width: *max_width,
                        line_height: *line_height,
                        alignment: *alignment,
                    });
                }
            }
        }

        // ── Process Audio Calls ──
        audio_calls.extend(entity.draw.audio_calls.iter().cloned());

        let iter = entity.draw.draw_calls.iter();

        let r = &entity.resolved;
        
        // Partition effects by scope
        let mut padded_effects = Vec::new();
        for effect in &entity.draw.effect_chain {
            match effect.scope {
                crate::schema::v2::ShaderScope::Camera => camera_effects.push(effect.clone()),
                crate::schema::v2::ShaderScope::Layer => {
                    layer_effects_map.entry(entity.id.clone())
                        .or_insert_with(Vec::new)
                        .push(effect.clone());
                }
                _ => padded_effects.push(effect.clone()),
            }
        }
        
        let has_effects = !padded_effects.is_empty();
        let pad = if has_effects { entity.draw.effect_padding } else { 0.0 };
        
        let diag = (r.width * r.width + r.height * r.height).sqrt();
        let ew = (diag * sx + pad * 2.0).max(1.0).ceil();
        let eh = (diag * sy + pad * 2.0).max(1.0).ceil();

        let (local_cam_x, local_cam_y) = if has_effects {
            (r.x - ew / (2.0 * sx), r.y - eh / (2.0 * sy))
        } else {
            (cam_x, cam_y)
        };

        let mut local_flat_list = Vec::new();

        for call in iter {
            // ── World units → pixel projection ──
            let w = call.width * sx;
            let h = call.height * sy;
            
            let cos_r = call.rotation.cos();
            let sin_r = call.rotation.sin();
            let dx = (0.5 - call.anchor_x) * w;
            let dy = (0.5 - call.anchor_y) * h;
            
            // Map world coordinates considering camera translation relative to top-left.
            let center_x = (call.x - local_cam_x) * sx + dx * cos_r - dy * sin_r;
            let center_y = (call.y - local_cam_y) * sy + dx * sin_r + dy * cos_r;
            let flat_x = center_x - w * 0.5;
            let flat_y = center_y - h * 0.5;

            // ── Fit mode UV parameters ──
            let iw = call.intrinsic_width;
            let ih = call.intrinsic_height;
            let (uv_offset, uv_scale) = call.fit_mode.calculate_uv(call.width, call.height, iw, ih, call.align_x, call.align_y);

            // Map Blend Mode string back to an ID, defaulting to Normal (0) if unmapped
            let blend_id = match call.blend_mode.to_lowercase().as_str() {
                "multiply" => 1,
                "screen" => 2,
                "overlay" => 3,
                "soft_light" => 4,
                "add" => 5,
                "difference" => 6,
                _ => 0,
            };

            let mut textures = Vec::new();
            if let Some(t) = &call.texture_key {
                textures.push(t.clone());
            }

            let shader = match call.kind {
                crate::ecs::components::draw::DrawKind::SolidRect => "shapes",
                crate::ecs::components::draw::DrawKind::SolidEllipse => "shapes",
                crate::ecs::components::draw::DrawKind::Texture => "composite",
                crate::ecs::components::draw::DrawKind::Text => "composite",
                crate::ecs::components::draw::DrawKind::Outline => "outline",
                crate::ecs::components::draw::DrawKind::Gizmo => "gizmo",
                crate::ecs::components::draw::DrawKind::CameraFrame => "composite",
                crate::ecs::components::draw::DrawKind::DashedRect => "dashed_rect",
            };

            let layer = if storages.get_component::<crate::ecs::components::CameraComponent>(&entity.id).is_some() { 9999 } else { entity.resolved.layer };
            
            // Force center of the local texture target if this goes to offscreen pass!
            let (target_x, target_y) = if has_effects {
                (ew * 0.5 - w * 0.5, eh * 0.5 - h * 0.5)
            } else {
                (flat_x, flat_y)
            };

            local_flat_list.push(FlatEntity {
                id: 0,
                x: target_x,
                y: target_y,
                width: w,
                height: h,
                rotation: call.rotation,
                opacity: if has_effects { 1.0 } else { call.opacity }, // Apply opacity at the end if effects are used
                blend_mode: blend_id,
                color: call.color,
                shader: shader.to_string(),
                textures,
                params: call.params.clone(),
                layer,
                z_index: layer as f32,
                fit_mode: match call.fit_mode {
                    crate::ecs::components::FitMode::Contain => 1,
                    crate::ecs::components::FitMode::Cover => 2,
                    _ => 0, // Stretch
                },
                uv_offset,
                uv_scale,
                intrinsic_width: iw,
                intrinsic_height: ih,
            });
        }

        if has_effects {
            let input_base_key = format!("_ent_src_{}", entity.id);
            passes.push(RenderPass {
                output: input_base_key.clone(),
                pass_type: PassType::Entities {
                    entities: local_flat_list,
                    clear_color: [0.0, 0.0, 0.0, 0.0],
                },
                target_width: Some(ew as u32),
                target_height: Some(eh as u32),
            });

            let mut current_key = input_base_key.clone();
            for (i, effect) in padded_effects.iter().enumerate() {
                let out_key = format!("_ent_fx_{}_{}", entity.id, i);
                passes.push(RenderPass {
                    output: out_key.clone(),
                    pass_type: PassType::Effect {
                        shader: effect.shader_id.clone(),
                        inputs: vec![current_key],
                        params: effect.params.clone(),
                    },
                    target_width: Some(ew as u32),
                    target_height: Some(eh as u32),
                });
                current_key = out_key;
                
                if effect.scope == crate::schema::v2::ShaderScope::Masked {
                    let masked_key = format!("_ent_masked_{}_{}", entity.id, i);
                    passes.push(RenderPass {
                        output: masked_key.clone(),
                        pass_type: PassType::Effect {
                            shader: "mask_composite".to_string(),
                            inputs: vec![current_key, input_base_key.clone()],
                            params: vec![0.0, 0.0, 0.0, 0.0],
                        },
                        target_width: Some(ew as u32),
                        target_height: Some(eh as u32),
                    });
                    current_key = masked_key;
                }
            }

            let layer = if storages.get_component::<crate::ecs::components::CameraComponent>(&entity.id).is_some() { 9999 } else { entity.resolved.layer };
            
            flat_entities.push(FlatEntity {
                id: 0,
                x: (r.x - cam_x) * sx - ew * 0.5,
                y: (r.y - cam_y) * sy - eh * 0.5,
                width: ew,
                height: eh,
                rotation: 0.0, // Pre-rotated inside offscreen
                opacity: r.opacity,
                blend_mode: 0,
                color: [1.0, 1.0, 1.0, 1.0],
                shader: "composite".to_string(),
                textures: vec![current_key],
                params: vec![],
                layer,
                z_index: layer as f32,
                fit_mode: 0,
                uv_offset: [0.0, 0.0],
                uv_scale: [1.0, 1.0],
                intrinsic_width: ew,
                intrinsic_height: eh,
            });
        } else {
            flat_entities.extend(local_flat_list);
        }

        // ── Handle Adjustment Layer Effects ──
        // If this entity has Layer scope effects, we must flush current flat_entities
        // to a composite buffer, apply the layer effects, and output it back.
        if let Some(layer_fx) = layer_effects_map.get(&entity.id) {
            if !flat_entities.is_empty() {
                // 1. Render all accumulated entities underneath this layer
                let src_key = format!("_layer_src_{}", entity.id);
                passes.push(RenderPass {
                    output: src_key.clone(),
                    pass_type: PassType::Entities {
                        entities: std::mem::take(&mut flat_entities), // FLUSHand clear
                        clear_color: [0.0, 0.0, 0.0, 0.0],
                    },
                    target_width: Some(screen_width),
                    target_height: Some(screen_height),
                });

                // 2. Apply effects to the accumulated frame
                let mut current_key = src_key;
                for (i, effect) in layer_fx.iter().enumerate() {
                    let out_key = format!("_layer_fx_{}_{}", entity.id, i);
                    passes.push(RenderPass {
                        output: out_key.clone(),
                        pass_type: PassType::Effect {
                            shader: effect.shader_id.clone(),
                            inputs: vec![current_key],
                            params: effect.params.clone(),
                        },
                        target_width: Some(screen_width),
                        target_height: Some(screen_height),
                    });
                    current_key = out_key;
                }

                // 3. Composite the resulting effect back into flat_entities as a fullscreen texture
                // Note: The Adjustment Layer entity's Rect masks the effect!
                // We use the entity's geometry (from `local_flat_list` but without drawing it directly)
                // Wait, if we use the entity's geometry, it acts as a stencil/mask for the fullscreen effect!
                // For simplicity, we just push the fullscreen effect over the background right now. 
                // A true masked adjustment layer needs a mask shader.
                // We'll just push it as a fullscreen textured rect.
                flat_entities.push(FlatEntity {
                    id: 0,
                    x: 0.0,
                    y: 0.0,
                    width: screen_width as f32,
                    height: screen_height as f32,
                    rotation: 0.0,
                    opacity: 1.0,
                    blend_mode: 0,
                    color: [1.0, 1.0, 1.0, 1.0],
                    shader: "composite".to_string(),
                    textures: vec![current_key],
                    params: vec![],
                    layer: entity.resolved.layer,
                    z_index: entity.resolved.layer as f32,
                    fit_mode: 0,
                    uv_offset: [0.0, 0.0],
                    uv_scale: [1.0, 1.0],
                    intrinsic_width: 0.0,
                    intrinsic_height: 0.0,
                });
            }
        }
    }

    // ── Build Main Screen RenderPass ──

    // If no camera effects, we output directly to "main"
    let base_output = if camera_effects.is_empty() {
        "main".to_string()
    } else {
        "_camera_src".to_string()
    };

    passes.push(RenderPass {
        output: base_output.clone(),
        pass_type: PassType::Entities {
            entities: flat_entities,
            clear_color: [0.0, 0.0, 0.0, 0.0]
        },
        target_width: if camera_effects.is_empty() { None } else { Some(screen_width) },
        target_height: if camera_effects.is_empty() { None } else { Some(screen_height) },
    });

    // Loop over camera effects
    let mut current_cam_key = base_output;
    for (i, effect) in camera_effects.iter().enumerate() {
        let out_key = if i == camera_effects.len() - 1 {
            "main".to_string() // Last effect writes directly to main
        } else {
            format!("_camera_fx_{}", i)
        };
        
        passes.push(RenderPass {
            output: out_key.clone(),
            pass_type: PassType::Effect {
                shader: effect.shader_id.clone(),
                inputs: vec![current_cam_key],
                params: effect.params.clone(),
            },
            target_width: if out_key == "main" { None } else { Some(screen_width) },
            target_height: if out_key == "main" { None } else { Some(screen_height) },
        });
        current_cam_key = out_key;
    }

    passes.push(RenderPass {
        output: "final".into(),
        pass_type: PassType::Output { input: "main".into() },
        target_width: None,
        target_height: None,
    });

    Frame {
        passes,
        texture_updates,
        audio_calls,
    }
}
