use crate::scene::MaterialV2;
use super::FitMode;

/// Runtime-only component containing draw instructions.
///
/// This component is dynamically generated by `source_sys` and `editor_sys` 
/// every frame. It is never serialized or saved to the scene JSON.
/// It acts as the universal primitive for the `render_sys`.
#[derive(Debug, Clone, Default)]
pub struct DrawComponent {
    pub draw_calls: Vec<DrawCall>,
    pub material_chain: Vec<MaterialV2>,
    pub texture_requests: Vec<TextureRequest>,
}

#[derive(Debug, Clone)]
pub struct DrawCall {
    pub kind: DrawKind,
    
    // Transform (World Space - after hierarchy cascade)
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
    pub rotation: f32, // in radians
    pub anchor_x: f32,
    pub anchor_y: f32,
    
    // Visual
    pub opacity: f32,
    pub blend_mode: String,
    pub align_x: f32,
    pub align_y: f32,
    
    // Content
    pub color: [f32; 4], // fill/tint color
    pub texture_key: Option<String>,
    pub shader: String,
    pub params: Vec<f32>,
    
    // Fit properties (for texture mappings)
    pub fit_mode: FitMode,
    pub intrinsic_width: f32,
    pub intrinsic_height: f32,
}

impl Default for DrawCall {
    fn default() -> Self {
        Self {
            kind: DrawKind::SolidRect,
            x: 0.0,
            y: 0.0,
            width: 0.0,
            height: 0.0,
            rotation: 0.0,
            anchor_x: 0.0,
            anchor_y: 0.0,
            opacity: 1.0,
            blend_mode: "normal".to_string(),
            align_x: 0.5,
            align_y: 0.5,
            color: [1.0, 1.0, 1.0, 1.0],
            texture_key: None,
            shader: "composite".to_string(),
            params: vec![],
            fit_mode: FitMode::Stretch,
            intrinsic_width: 0.0,
            intrinsic_height: 0.0,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DrawKind {
    SolidRect,
    SolidEllipse,
    Texture,
    Text,
    Outline,
    Gizmo,
    CameraFrame,
    DashedRect,
}

#[derive(Debug, Clone)]
pub enum TextureRequest {
    DecodeVideoFrame {
        key: String,
        asset_url: String,
        timestamp_secs: f64,
    },
    LoadImage {
        key: String,
        asset_url: String,
    },
    RasterizeText {
        key: String,
        content: String,
        font_size: f32,
        color: [f32; 4],
        font_key: Option<String>,
        max_width: Option<f32>,
        line_height: Option<f32>,
        alignment: u32,
    },
}
